INCLUDES += -Icontrib/freestanding/libcxx/include
SRCS += contrib/freestanding/libcxx/src/algorithm.cpp
SRCS += contrib/freestanding/libcxx/src/exception.cpp
SRCS += contrib/freestanding/libcxx/src/memory.cpp
SRCS += contrib/freestanding/libcxx/src/random.cpp
SRCS += contrib/freestanding/libcxx/src/string.cpp
SRCS += contrib/freestanding/libcxx/src/typeinfo.cpp
SRCS += contrib/freestanding/libcxx/src/utility.cpp
