HDRS +=	include/util/c_string_ptr-inl.h					\
	include/util/c_string_ptr.h					\
	include/util/string_piece-inl.h					\
	include/util/string_piece.h					\
	include/util/cpp/identifier.h					\
	include/util/cpp/name-inl.h					\
	include/util/cpp/name.h						\
	include/util/cpp/namespace-inl.h				\
	include/util/cpp/namespace.h

SRCS +=	src/c_string_ptr.cc						\
	src/string_piece.cc						\
	src/cpp_identifier.cc						\
	src/cpp_name.cc							\
	src/cpp_namespace.cc
