INCLUDES += -Ic_util/include
SRCS +=	c_util/src/c_string_ptr.cc					\
	c_util/src/string_piece.cc					\
	c_util/src/cpp_function.cc					\
	c_util/src/cpp_identifier.cc					\
	c_util/src/cpp_name.cc						\
	c_util/src/cpp_namespace.cc					\
	c_util/src/cpp_template.cc
