INCLUDES_LOADER += -Iloader/include

SRCS_LOADER += loader/src/loader.s
SRCS_LOADER += loader/src/amd64_boot.cc
SRCS_LOADER += loader/src/loader_kernel.cc
SRCS_LOADER += loader/src/loader_support.cc
SRCS_LOADER += loader/src/loader_x86_video.cc
SRCS_LOADER += loader/src/loader_abi.cc
